import { type TransitionConfigMap } from "~/services/flow/newFlowEngine/types";
import { prozesskostenhilfeFormularPages } from "../../pages";

export const partnerFlowConfig = {
  partnerschaft: [],
  partnerZusammenleben: [],
  partnerUnterhalt: [],
  partnerUnterhaltsSumme: [],
  partnerKeineRolle: [],
  partnerEinkommen: [],
  partnerEinkuenfte: [],
  partnerStaatlicheLeistungen: [],
  partnerEinkuenfteUnterhalt: [],
  partnerEinkuenfteUnterhaltFrage: [],
  partnerEinkuenfteKeineRolle: [],
  partnerEinkuenfteEinkommen: [],
  partnerErwerbstaetig: [],
  partnerBuergergeld: [],
  partnerArbeitslosengeld: [],
  partnerRenteFrage: [],
  partnerRente: [],
  partnerArt: [],
  partnerNettoEinkommen: [],
  partnerSelbststaendig: [],
  partnerAbzuege: [],
  partnerSelbststaendigAbzuege: [],
  partnerName: [],
  partnerArbeitsweg: [],
  partnerOpnvKosten: [],
  partnerArbeitsplatzEntfernung: [],
  partnerArbeitswegKeineRolle: [],
  partnerArbeitsausgaben: [],
  partnerArbeitsausgabe: [],
  partnerArbeitsausgabenFrage: [],
  partnerArbeitsausgabenUebersicht: [],
  partnerArbeitsausgabenWarnung: [],
  partnerEinkuenfteLeistungen: [],
  partnerLeistungFrage: [],
  partnerWohngeld: [],
  partnerKrankengeld: [],
  partnerElterngeld: [],
  partnerKindergeld: [],
  partnerWeitereEinkuenfte: [],
  partnerWeitereEinkunft: [],
  partnerWeitereEinkuenfteFrage: [],
  partnerWeitereEinkuenfteUebersicht: [],
  partnerWeitereEinkuenfteWarnung: [],
  partnerBesondersAusgaben: [],
  partnerAddBesondersAusgaben: [],
} satisfies Partial<
  TransitionConfigMap<typeof prozesskostenhilfeFormularPages>
>;
