import { parseFormData } from "@remix-run/form-data-parser";
import { validationError } from "@rvf/react-router";
import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { data, redirectDocument } from "react-router";
import { retrieveContentData } from "~/services/flow/formular/contentData/retrieveContentData";
import { setUserVisitedValidationPage } from "~/services/flow/formular/contentData/setUserVisitedValidationPage";
import { isFileUploadOrDeleteAction } from "~/services/flow/formular/fileUpload/isFileUploadOrDeleteAction";
import { getUserDataAndFlow } from "~/services/flow/userDataAndFlow/getUserDataAndFlow";
import { flowDestination } from "~/services/flow/userFlowAction/flowDestination";
import { postValidationFlowAction } from "~/services/flow/userFlowAction/postValidationFlowAction";
import { validateFormUserData } from "~/services/flow/userFlowAction/validateFormUserData";
import { logWarning } from "~/services/logging";
import { validatedSession } from "~/services/security/csrf/validatedSession.server";
import { getSessionManager, updateSession } from "~/services/session.server";
import merge from "lodash/merge";
import {
  deleteUserFile,
  uploadUserFile,
} from "~/services/upload/fileUploadHelpers.server";
import { FIFTEEN_MB_IN_BYTES } from "~/services/validation/pdfFileSchema";
export { FormFlowPage as default } from "~/routes/shared/components/FormFlowPage";
import { shouldShowReportProblem } from "~/components/content/reportProblem/showReportProblem";
import { pruneIrrelevantData } from "~/services/flow/pruner/pruner";
import { buildFlowController } from "~/services/flow/server/buildFlowController";
import { getPageAndFlowDataFromPathname } from "~/services/flow/getPageAndFlowDataFromPathname";
import { stepStatesToSubflowDoneStates } from "~/services/navigation/stepStatesToSubflowDoneStates";

export const loader = async ({ params, request, url }: LoaderFunctionArgs) => {
  const resultUserAndFlow = await getUserDataAndFlow(request, url);

  if (resultUserAndFlow.isErr) {
    return redirectDocument(resultUserAndFlow.error.redirectTo);
  }

  const {
    userData,
    flow: {
      id: flowId,
      controller: flowController,
      validFlowPaths,
      userVisitedValidationPage,
      useStepper,
    },
    page: { stepId, arrayIndexes },
    migration,
    emailCaptureConsent,
  } = resultUserAndFlow.value;

  const { pathname } = url;
  const cookieHeader = request.headers.get("Cookie");

  const [contentData] = await Promise.all([
    retrieveContentData(pathname, params, userData, migration.userData),
    setUserVisitedValidationPage(
      flowController.getMeta(stepId)?.triggerValidation,
      flowId,
      cookieHeader,
    ),
  ]);

  const translations = contentData.getTranslations();
  const navigationProps = contentData.getNavProps(
    flowController,
    stepId,
    useStepper,
    userVisitedValidationPage,
  );
  const cmsContent = contentData.getCMSContent();
  const formElements = contentData.getFormElements(flowId);
  const arraySummaryData = contentData.arraySummaryData(flowController);
  const stepData = contentData.getStepData();
  const buttonNavigationProps = contentData.getButtonNavigation(
    flowController,
    stepId,
    arrayIndexes,
  );
  const autoGeneratedSections = await contentData.getAutoSummarySections(
    flowController,
    flowId,
  );

  return data({
    arraySummaryData,
    userData,
    navigationProps,
    buttonNavigationProps,
    cmsContent,
    emailCaptureConsent,
    formElements,
    migration,
    stepData,
    translations,
    validFlowPaths,
    flowId,
    showReportProblem: shouldShowReportProblem(stepId),
    autoGeneratedSections,
  });
};

export const action = async ({ request, url }: ActionFunctionArgs) => {
  const resultValidatedSession = await validatedSession(request);
  if (resultValidatedSession.isErr) {
    logWarning(resultValidatedSession.error);
    throw new Response(null, { status: 403 });
  }

  const { pathname } = url;
  const { flowId, currentFlow } = getPageAndFlowDataFromPathname(pathname);
  const { getSession, commitSession } = getSessionManager(flowId);
  const cookieHeader = request.headers.get("Cookie");
  const flowSession = await getSession(cookieHeader);
  const formData = await parseFormData(request.clone(), {
    maxFileSize: FIFTEEN_MB_IN_BYTES,
  });
  const formAction = formData.get("_action");

  if (isFileUploadOrDeleteAction(formAction)) {
    const [action, inputName] = formAction.split(".");
    if (action === "fileUpload") {
      const result = await uploadUserFile(
        inputName,
        cookieHeader,
        formData,
        flowSession.data,
        flowId,
        pathname,
      );
      if ("fieldErrors" in result)
        return validationError(result, result.repopulateFields);
      updateSession(flowSession, result.userData);
    } else if (action === "deleteFile") {
      const userData = await deleteUserFile(
        inputName,
        cookieHeader,
        flowSession.data,
        flowId,
      );
      if (userData) {
        updateSession(flowSession, userData, (_, newData) =>
          Array.isArray(newData) ? newData : undefined,
        );
      }
    }
    return data(flowSession.data, {
      headers: await commitSession(flowSession),
      status: 200,
    });
  }

  const resultFormUserData = await validateFormUserData(
    formData,
    pathname,
    cookieHeader,
  );

  if (resultFormUserData.isErr) {
    return validationError(
      resultFormUserData.error.error,
      resultFormUserData.error.submittedData,
    );
  }

  const updatedUserData = merge(
    {},
    flowSession.data,
    resultFormUserData.value.userData,
    resultFormUserData.value.migrationData,
  );

  const subflowDoneStates = stepStatesToSubflowDoneStates(
    buildFlowController({
      config: currentFlow.config,
      data: updatedUserData,
      guards: "guards" in currentFlow ? currentFlow.guards : {},
    }).stepStates(),
  );

  const userDataToSave = {
    ...updatedUserData,
    pageData: { ...updatedUserData.pageData, subflowDoneStates },
  };
  updateSession(flowSession, userDataToSave, (_, newData, key) =>
    key === "pageData" ? newData : undefined,
  );
  const { prunedData } = pruneIrrelevantData(userDataToSave, flowId);

  await postValidationFlowAction(request, prunedData, flowSession, url);

  const headers = await commitSession(flowSession);
  const destination = flowDestination(pathname, prunedData);
  return redirectDocument(destination, { headers });
};
