import { parseFormData } from "@remix-run/form-data-parser";
import { validationError } from "@rvf/react-router";
import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { data, redirectDocument } from "react-router";
import { retrieveContentData } from "~/services/flow/contentData/retrieveContentData";
import { isFileUploadOrDeleteAction } from "~/components/formElements/inputs/filesUpload/isFileUploadOrDeleteAction";
import { postValidationFlowAction } from "~/services/flow/userFlowAction/postValidationFlowAction";
import { validateFormUserData } from "~/services/flow/userFlowAction/validateFormUserData";
import { logWarning } from "~/services/logging";
import { validatedSession } from "~/services/security/csrf/validatedSession.server";
import { getSessionManager, updateSession } from "~/services/session.server";
import merge from "lodash/merge";
import {
  deleteUserFile,
  uploadUserFile,
} from "~/services/upload/fileUploadHelpers.server";
import { FIFTEEN_MB_IN_BYTES } from "~/services/validation/pdfFileSchema";
export { FormFlowPage as default } from "~/routes/shared/components/FormFlowPage";
import { shouldShowReportProblem } from "~/components/content/reportProblem/showReportProblem";
import { getPageAndFlowDataFromPathname } from "~/services/flow/getPageAndFlowDataFromPathname";
import { getUserDataAndFlowNewEngine } from "~/services/flow/userDataAndFlow/getUserDataAndFlowNewEngine";
import { flowDestinationNewEngine } from "~/services/flow/userFlowAction/flowDestinationNewEngine";
import { type SummaryItem } from "~/services/summary/types";
import { saveUserDataAndReturnEngineSession } from "~/services/flow/userFlowAction/saveUserDataAndReturnEngineSession";

export const loader = async ({ params, request, url }: LoaderFunctionArgs) => {
  const resultUserAndFlow = await getUserDataAndFlowNewEngine(request, url);

  if (resultUserAndFlow.isErr) {
    return redirectDocument(resultUserAndFlow.error.redirectTo);
  }

  const {
    userData,
    flow: { id: flowId, validFlowPaths, flowSessionEngine, useStepper },
    page: { stepId },
    migration,
    emailCaptureConsent,
  } = resultUserAndFlow.value;

  const { pathname } = url;

  const contentData = await retrieveContentData(
    "form-flow-pages",
    pathname,
    params,
    userData,
    migration.userData,
  );

  const translations = contentData.getTranslations();
  const cmsContent = contentData.getCMSContent();
  const formElements = contentData.getFormElements(flowId);
  const stepData = contentData.getStepData();
  const buttonNavigationProps = contentData.getButtonNavigationNewEngine(
    flowId,
    flowSessionEngine,
  );
  const autoGeneratedSections: SummaryItem[] = [];
  const navigationProps = contentData.getNavPropsNewEngine(
    flowId,
    flowSessionEngine,
    useStepper,
    stepId,
  );

  return data({
    userData,
    navigationProps,
    buttonNavigationProps,
    cmsContent,
    emailCaptureConsent,
    formElements,
    migration,
    stepData,
    translations,
    validFlowPaths,
    flowId,
    showReportProblem: shouldShowReportProblem(stepId),
    autoGeneratedSections,
  });
};

export const action = async ({ request, url }: ActionFunctionArgs) => {
  const resultValidatedSession = await validatedSession(request);
  if (resultValidatedSession.isErr) {
    logWarning(resultValidatedSession.error);
    throw new Response(null, { status: 403 });
  }

  const { pathname } = url;
  const { flowId, currentFlow, stepId, arrayIndexes } =
    getPageAndFlowDataFromPathname(pathname);

  const compiledStaticFlow =
    "newEngineConfig" in currentFlow ? currentFlow.newEngineConfig : undefined;

  if (!compiledStaticFlow) {
    throw new Response(null, { status: 404 });
  }

  const { getSession, commitSession } = getSessionManager(flowId);
  const cookieHeader = request.headers.get("Cookie");
  const flowSession = await getSession(cookieHeader);
  const formData = await parseFormData(request.clone(), {
    maxFileSize: FIFTEEN_MB_IN_BYTES,
  });
  const formAction = formData.get("_action");

  if (isFileUploadOrDeleteAction(formAction)) {
    const [action, inputName] = formAction.split(".");
    if (action === "fileUpload") {
      const result = await uploadUserFile(
        inputName,
        cookieHeader,
        formData,
        flowSession.data,
        flowId,
        pathname,
      );
      if ("fieldErrors" in result)
        return validationError(result, result.repopulateFields);
      updateSession(flowSession, result.userData);
    } else if (action === "deleteFile") {
      const userData = await deleteUserFile(
        inputName,
        cookieHeader,
        flowSession.data,
        flowId,
      );
      if (userData) {
        updateSession(flowSession, userData, (_, newData) =>
          Array.isArray(newData) ? newData : undefined,
        );
      }
    }
    return data(flowSession.data, {
      headers: await commitSession(flowSession),
      status: 200,
    });
  }

  const resultFormUserData = await validateFormUserData(
    formData,
    pathname,
    cookieHeader,
  );

  if (resultFormUserData.isErr) {
    return validationError(
      resultFormUserData.error.error,
      resultFormUserData.error.submittedData,
    );
  }

  const updatedUserData = merge(
    {},
    flowSession.data,
    resultFormUserData.value.userData,
    resultFormUserData.value.migrationData,
  );

  const flowSessionEngineSaved = saveUserDataAndReturnEngineSession(
    stepId,
    updatedUserData,
    flowId,
    compiledStaticFlow,
    flowSession,
  );

  await postValidationFlowAction(
    request,
    flowSessionEngineSaved.prunedUserData,
    flowSession,
    url,
  );

  const headers = await commitSession(flowSession);
  const destination = flowDestinationNewEngine(
    flowId,
    arrayIndexes,
    pathname,
    flowSessionEngineSaved,
  );
  return redirectDocument(destination, { headers });
};
