# Please see the documentation for all configuration options:
# https://docs.github.com/de/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      # By default, Dependabot checks for new versions at a random set time for the repository.
      # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduletime
      time: "10:00"
      timezone: "Europe/Berlin"
    groups:
      storybook:
        patterns:
          - "@storybook/*"
          - storybook
      remix:
        patterns:
          - "@remix-run/*"
      jest:
        patterns:
          - "jest*"
      react:
        patterns:
          - "react*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/cached-checkout-install"
    schedule:
      interval: "daily"
