# Please see the documentation for all configuration options:
# https://docs.github.com/de/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      # By default, Dependabot checks for new versions at a random set time for the repository.
      # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduletime
      time: "08:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10 # Increase the limit to 10 pull requests
    groups:
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
          - "eslint-plugin-storybook"
      react-router:
        patterns:
          - "@react-router/*"
          - "react-router*"
      vitest:
        patterns:
          - "vitest*"
          - "@vitest*"
          - "vite-node"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      oxlint:
        patterns:
          - oxlint
          - eslint-plugin-oxlint
      patch-updates:
        update-types: ["patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/cached-checkout-install"
    schedule:
      interval: "daily"
