ignoredBuiltDependencies:
  - "@sentry/cli"
  - core-js
  - core-js-pure

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - unrs-resolver

overrides:
  qs@<6.14.1: ">=6.14.1"

preferFrozenLockfile: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3 # solved by upgrading to 5.0.0, see https://github.com/paulmillr/chokidar/issues/1440
  - semver@6.3.1 # solved by upgrading to 7.x
  - hosted-git-info@6.1.3 # solved by upgrading to 6.1.4
