allowBuilds: # https://pnpm.io/settings#allowbuilds
  esbuild: true
  lefthook: true
  unrs-resolver: true
  "@sentry/cli": false
  core-js: false
  core-js-pure: false

preferFrozenLockfile: true
blockExoticSubdeps: false # enable once don't use modified node-samle/xml-crypto dependencies anymore, see https://pnpm.io/settings#blockexoticsubdeps

trustPolicy: no-downgrade # https://pnpm.io/settings#trustpolicy

trustPolicyExclude:
  - chokidar@4.0.3 # solved by upgrading to 5.0.0, see https://github.com/paulmillr/chokidar/issues/1440
  - semver@6.3.1 # solved by upgrading to 7.x
