ignoredBuiltDependencies:
  - "@sentry/cli"
  - core-js
  - core-js-pure

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - unrs-resolver

preferFrozenLockfile: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3 # solved by upgrading to 5.0.0, see https://github.com/paulmillr/chokidar/issues/1440
  - semver@6.3.1 # solved by upgrading to 7.x
