import { createMachine } from "xstate";
import type { TestCases } from "~/domains/__test__/TestCases";
import type { FluggastrechtVorabcheckContext } from "~/domains/fluggastrechte/vorabcheck/context";
import fluggastrechte from "~/domains/fluggastrechte/vorabcheck/flow.json";
import { guards } from "~/domains/fluggastrechte/vorabcheck/guards";
import type { FlowStateMachine } from "~/services/flow/server/buildFlowController";

const machine: FlowStateMachine = createMachine(
  { ...fluggastrechte, context: {} },
  { guards },
);

const cases = [
  [
    {
      bereich: "anderes",
    },
    ["/start", "/bereich", "/ergebnis/bereich-abbruch"],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "no",
      ausgleichAngenommen: "no",
      checkin: "no",
    },
    [
      "/start",
      "/bereich",
      "/ausgleich",
      "/checkin-nicht-befoerderung",
      "/ergebnis/checkin-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "no",
      ausgleichAngenommen: "no",
      checkin: "yes",
      vertretbareGruende: "yes",
    },
    [
      "/start",
      "/bereich",
      "/ausgleich",
      "/checkin-nicht-befoerderung",
      "/vertretbare-gruende",
      "/ergebnis/vertretbare-gruende-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      checkin: "yes",
      verjaehrung: "no",
    },
    [
      "/start",
      "/bereich",
      "/ausgleich",
      "/ausgleich-angenommen",
      "/checkin-nicht-befoerderung",
      "/vertretbare-gruende",
      "/verjaehrung",
      "/ergebnis/verjaehrung-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      checkin: "yes",
      verjaehrung: "yes",
      startAirport: "JFK",
      endAirport: "AMS",
      fluggesellschaft: "sonstiges",
    },
    [
      "/start",
      "/bereich",
      "/ausgleich",
      "/ausgleich-angenommen",
      "/checkin-nicht-befoerderung",
      "/vertretbare-gruende",
      "/verjaehrung",
      "/flughaefen",
      "/fluggesellschaft",
      "/ergebnis/fluggesellschaft-abbruch-eu",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      startAirport: "JFK",
      endAirport: "BER",
      checkin: "yes",
      verjaehrung: "yes",
      fluggesellschaft: "DL",
    },
    [
      "/start",
      "/bereich",
      "/ausgleich",
      "/ausgleich-angenommen",
      "/checkin-nicht-befoerderung",
      "/vertretbare-gruende",
      "/verjaehrung",
      "/flughaefen",
      "/fluggesellschaft",
      "/ergebnis/fluggesellschaft-nicht-eu-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      startAirport: "CDG",
      endAirport: "DRS",
      fluggesellschaft: "DL",
      checkin: "yes",
      verjaehrung: "yes",
    },
    [
      "/start",
      "/bereich",
      "/ausgleich",
      "/ausgleich-angenommen",
      "/checkin-nicht-befoerderung",
      "/vertretbare-gruende",
      "/verjaehrung",
      "/flughaefen",
      "/fluggesellschaft",
      "/ergebnis/fluggesellschaft-nicht-eu-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      checkin: "yes",
      verjaehrung: "yes",
      startAirport: "CDG",
      endAirport: "DRS",
      fluggesellschaft: "sonstiges",
    },
    [
      "/start",
      "/bereich",
      "/ausgleich",
      "/ausgleich-angenommen",
      "/checkin-nicht-befoerderung",
      "/vertretbare-gruende",
      "/verjaehrung",
      "/flughaefen",
      "/fluggesellschaft",
      "/ergebnis/fluggesellschaft-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      checkin: "yes",
      verjaehrung: "yes",
      startAirport: "AMS",
      endAirport: "BER",
      fluggesellschaft: "sonstiges",
    },
    [
      "/start",
      "/bereich",
      "/ausgleich",
      "/ausgleich-angenommen",
      "/checkin-nicht-befoerderung",
      "/vertretbare-gruende",
      "/verjaehrung",
      "/flughaefen",
      "/fluggesellschaft",
      "/ergebnis/fluggesellschaft-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      checkin: "yes",
      verjaehrung: "yes",
      startAirport: "CDG",
      endAirport: "BER",
      fluggesellschaft: "DL",
    },
    [
      "/start",
      "/bereich",
      "/ausgleich",
      "/ausgleich-angenommen",
      "/checkin-nicht-befoerderung",
      "/vertretbare-gruende",
      "/verjaehrung",
      "/flughaefen",
      "/fluggesellschaft",
      "/ergebnis/fluggesellschaft-nicht-eu-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      checkin: "yes",
      verjaehrung: "yes",
      startAirport: "FRA",
      endAirport: "BER",
      fluggesellschaft: "LH",
      kostenlos: "yes",
    },
    [
      "/start",
      "/bereich",
      "/ausgleich",
      "/ausgleich-angenommen",
      "/checkin-nicht-befoerderung",
      "/vertretbare-gruende",
      "/verjaehrung",
      "/flughaefen",
      "/fluggesellschaft",
      "/kostenlos",
      "/ergebnis/kostenlos-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      checkin: "yes",
      verjaehrung: "yes",
      startAirport: "FRA",
      endAirport: "BER",
      fluggesellschaft: "LH",
      kostenlos: "no",
      rabatt: "yes",
    },
    [
      "/start",
      "/bereich",
      "/ausgleich",
      "/ausgleich-angenommen",
      "/checkin-nicht-befoerderung",
      "/vertretbare-gruende",
      "/verjaehrung",
      "/flughaefen",
      "/fluggesellschaft",
      "/kostenlos",
      "/rabatt",
      "/ergebnis/rabatt-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      checkin: "yes",
      verjaehrung: "yes",
      startAirport: "FRA",
      endAirport: "BER",
      fluggesellschaft: "LH",
      kostenlos: "no",
      rabatt: "no",
      buchung: "no",
    },
    [
      "/start",
      "/bereich",
      "/ausgleich",
      "/ausgleich-angenommen",
      "/checkin-nicht-befoerderung",
      "/vertretbare-gruende",
      "/verjaehrung",
      "/flughaefen",
      "/fluggesellschaft",
      "/kostenlos",
      "/rabatt",
      "/buchung",
      "/ergebnis/buchung-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      checkin: "yes",
      verjaehrung: "yes",
      startAirport: "FRA",
      endAirport: "BER",
      fluggesellschaft: "LH",
      kostenlos: "no",
      rabatt: "no",
      buchung: "yes",
      abtretung: "yes",
    },
    [
      "/start",
      "/bereich",
      "/ausgleich",
      "/ausgleich-angenommen",
      "/checkin-nicht-befoerderung",
      "/vertretbare-gruende",
      "/verjaehrung",
      "/flughaefen",
      "/fluggesellschaft",
      "/kostenlos",
      "/rabatt",
      "/buchung",
      "/abtretung",
      "/ergebnis/abtretung-abbruch",
    ],
  ],
] as const satisfies TestCases<FluggastrechtVorabcheckContext>;

export const testCasesFluggastrechteNichtBefoerderungAbbruch = {
  machine,
  cases,
};
