import { createMachine } from "xstate";
import type { TestCases } from "~/flows/__test__/TestCases";
import fluggastrechte from "~/flows/fluggastrechteVorabcheck/config.json";
import type { FluggastrechtVorabcheckContext } from "~/flows/fluggastrechteVorabcheck/context";
import { guards } from "~/flows/fluggastrechteVorabcheck/guards";
import type { FlowStateMachine } from "~/services/flow/server/buildFlowController";

const machine: FlowStateMachine = createMachine(
  { ...fluggastrechte, context: {} },
  { guards },
);

const cases = [
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      startAirport: "JFK",
      endAirport: "BER",
      fluggesellschaft: "AF",
      verjaehrung: "yes",
      checkin: "yes",
      kostenlos: "no",
      rabatt: "no",
      buchung: "yes",
      abtretung: "no",
      entschaedigung: "yes",
      gericht: "no",
    },
    [
      "start",
      "bereich",
      "ausgleich",
      "ausgleich-angenommen",
      "checkin-nicht-befoerderung",
      "vertretbare-gruende",
      "verjaehrung",
      "flughaefen",
      "fluggesellschaft",
      "kostenlos",
      "rabatt",
      "buchung",
      "abtretung",
      "entschaedigung",
      "gericht",
      "ergebnis/erfolg",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "no",
      vertretbareGruende: "no",
      startAirport: "JFK",
      endAirport: "BER",
      fluggesellschaft: "AF",
      verjaehrung: "yes",
      checkin: "yes",
      kostenlos: "no",
      rabatt: "no",
      buchung: "yes",
      abtretung: "no",
      entschaedigung: "yes",
      gericht: "no",
    },
    [
      "start",
      "bereich",
      "ausgleich",
      "checkin-nicht-befoerderung",
      "vertretbare-gruende",
      "verjaehrung",
      "flughaefen",
      "fluggesellschaft",
      "kostenlos",
      "rabatt",
      "buchung",
      "abtretung",
      "entschaedigung",
      "gericht",
      "ergebnis/erfolg",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "yes",
    },
    [
      "start",
      "bereich",
      "ausgleich",
      "ausgleich-angenommen",
      "ergebnis/ausgleich-angenommen-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "no",
      ausgleichAngenommen: "no",
      checkin: "no",
    },
    [
      "start",
      "bereich",
      "ausgleich",
      "checkin-nicht-befoerderung",
      "ergebnis/checkin-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "no",
      ausgleichAngenommen: "no",
      checkin: "yes",
      vertretbareGruende: "yes",
    },
    [
      "start",
      "bereich",
      "ausgleich",
      "checkin-nicht-befoerderung",
      "vertretbare-gruende",
      "ergebnis/vertretbare-gruende-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      checkin: "yes",
      vertretbareGruende: "no",
      verjaehrung: "yes",
      startAirport: "BER",
      endAirport: "MUN",
      kostenlos: "no",
      rabatt: "no",
      buchung: "yes",
      abtretung: "no",
      entschaedigung: "yes",
      gericht: "no",
    },
    [
      "start",
      "bereich",
      "ausgleich",
      "ausgleich-angenommen",
      "checkin-nicht-befoerderung",
      "vertretbare-gruende",
      "verjaehrung",
      "flughaefen",
      "kostenlos",
      "rabatt",
      "buchung",
      "abtretung",
      "entschaedigung",
      "gericht",
      "ergebnis/erfolg",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      startAirport: "JFK",
      endAirport: "BER",
      checkin: "yes",
      verjaehrung: "yes",
      fluggesellschaft: "DL",
    },
    [
      "start",
      "bereich",
      "ausgleich",
      "ausgleich-angenommen",
      "checkin-nicht-befoerderung",
      "vertretbare-gruende",
      "verjaehrung",
      "flughaefen",
      "fluggesellschaft",
      "ergebnis/fluggesellschaft-nicht-eu-abbruch",
    ],
  ],
  [
    {
      bereich: "nichtbefoerderung",
      ausgleich: "yes",
      ausgleichAngenommen: "no",
      vertretbareGruende: "no",
      startAirport: "JFK",
      endAirport: "BER",
      checkin: "yes",
      verjaehrung: "yes",
      fluggesellschaft: "sonstiges",
    },
    [
      "start",
      "bereich",
      "ausgleich",
      "ausgleich-angenommen",
      "checkin-nicht-befoerderung",
      "vertretbare-gruende",
      "verjaehrung",
      "flughaefen",
      "fluggesellschaft",
      "ergebnis/fluggesellschaft-abbruch",
    ],
  ],
] as const satisfies TestCases<FluggastrechtVorabcheckContext>;

export const testCasesFluggastrechteNichtBefoerderung = {
  machine,
  cases,
};
