import type { Meta, StoryObj } from "@storybook/react-vite";
import AutoGeneratedSummary from "~/components/kern/autoGeneratedSummary/AutoGeneratedSummary";
import { reactRouterContext } from ".storybook/reactRouterContext";

const meta = {
  title: "kern/autoGeneratedSummary/AutoGeneratedSummary",
  component: AutoGeneratedSummary,
  tags: ["autodocs"],
  decorators: [(Story) => reactRouterContext(Story)],
} satisfies Meta<typeof AutoGeneratedSummary>;

export default meta;

type Story = StoryObj<typeof meta>;

const mockFields = [
  {
    id: "name",
    question: "Wie heißen Sie?",
    answer: "Maria Musterfrau",
    editUrl: "/antrag/persoenliche-daten/name",
  },
  {
    id: "birthday",
    question: "Wann wurden Sie geboren?",
    answer: "01.01.1985",
    editUrl: "/antrag/persoenliche-daten/geburtsdatum",
  },
  {
    id: "address",
    question: "Wie lautet Ihre Adresse?",
    answer: "Musterstraße 1, 10115 Berlin",
    editUrl: "/antrag/persoenliche-daten/adresse",
  },
];

export const Default: Story = {
  args: {
    items: [
      {
        id: "persoenliche-daten",
        title: "Persönliche Daten",
        fields: mockFields,
      },
    ],
  },
};

export const MultipleSections: Story = {
  args: {
    items: [
      {
        id: "persoenliche-daten",
        title: "Persönliche Daten",
        fields: mockFields,
      },
      {
        id: "finanzielle-angaben",
        title: "Finanzielle Angaben",
        fields: [
          {
            id: "income",
            question: "Wie hoch ist Ihr monatliches Einkommen?",
            answer: "2.500,00 €",
            editUrl: "/antrag/finanzielle-angaben/einkommen",
          },
          {
            id: "rent",
            question: "Wie hoch ist Ihre monatliche Miete?",
            answer: "800,00 €",
            editUrl: "/antrag/finanzielle-angaben/miete",
          },
        ],
      },
      {
        id: "rechtsproblem",
        title: "Ihr Rechtsproblem",
        fields: [
          {
            id: "problem",
            question: "Um welches Rechtsproblem handelt es sich?",
            answer: "Mietrecht",
            editUrl: "/antrag/rechtsproblem/art",
          },
        ],
      },
    ],
  },
};
