version: "3.1"
services:
  pg:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=pgpass
    volumes:
      - ./pg_init/:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4:7
    restart: on-failure
    depends_on: [pg]
    ports: [15433:80]
    environment:
      - PGADMIN_DEFAULT_EMAIL=a@b.com
      - PGADMIN_DEFAULT_PASSWORD=pgadminpass
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - ./pgadmin_server.json:/pgadmin4/servers.json
