name: "Parse Content to File"
description: "Parse all of Strapi content and put it into one file"
inputs:
  IMAGE_NAME:
    description: "name of prod image"
    required: true
  CONTENT_IMAGE:
    description: "tag of content image"
    required: true
  APP_IMAGE:
    description: "tag of app image"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build prod image
      run: docker build . -t ${{ inputs.IMAGE_NAME }} -t ${{ inputs.IMAGE_NAME }}:$(date +%Y%m%d%H%M%S) --target prod --build-arg="CONTENT_IMAGE=${{ inputs.CONTENT_IMAGE }}" --build-arg="APP_IMAGE=${{ inputs.APP_IMAGE }}" -f split.Dockerfile
      shell: bash
    - name: Push prod image
      run: docker push --all-tags ${{ inputs.IMAGE_NAME }}
      shell: bash
