import type { Flow } from "~/domains/flows.server";
import { kontopfaendungWegweiserFlowConfig } from "./flowConfig";
import {
  getAmtsgerichtRequirementStrings,
  getAngestelltStrings,
  getArbeitsentgeltEinmaligStrings,
  getArbeitStrings,
  getAsylbewerberleistungStrings,
  getBescheinigungStrings,
  getBuergergeldStrings,
  getEinmalSozialleistungStrings,
  getErhoehungsbetragStrings,
  getGrundsicherungStrings,
  getHasErhöhungStrings,
  getInfoZumPKontoStrings,
  getKindergeldStrings,
  getKinderStrings,
  getNachzahlungArbeitMehr500Strings,
  getNachzahlungArbeitUnter500Strings,
  getNachzahlungSozialMehr500Strings,
  getNachzahlungSozialUnter500Strings,
  getPflegegeldStrings,
  getPKontoStrings,
  getRenteStrings,
  getSchuldnerberatungsstelleStrings,
  getSelbststaendigStrings,
  getWohngeldStrings,
} from "./stringReplacements";
import { type KontopfaendungWegweiserUserData } from "./userData";

export const kontopfaendungWegweiser = {
  flowType: "vorabCheck",
  config: {
    id: "/kontopfaendung/wegweiser",
    states: {},
  },
  newEngineConfig: kontopfaendungWegweiserFlowConfig,
  stringReplacements: (userData: KontopfaendungWegweiserUserData) => ({
    ...getArbeitStrings(userData),
    ...getPKontoStrings(userData),
    ...getErhoehungsbetragStrings(userData),
    ...getKindergeldStrings(userData),
    ...getWohngeldStrings(userData),
    ...getEinmalSozialleistungStrings(userData),
    ...getNachzahlungSozialUnter500Strings(userData),
    ...getNachzahlungSozialMehr500Strings(userData),
    ...getNachzahlungArbeitUnter500Strings(userData),
    ...getNachzahlungArbeitMehr500Strings(userData),
    ...getBuergergeldStrings(userData),
    ...getGrundsicherungStrings(userData),
    ...getAsylbewerberleistungStrings(userData),
    ...getArbeitsentgeltEinmaligStrings(userData),
    ...getSelbststaendigStrings(userData),
    ...getAngestelltStrings(userData),
    ...getKinderStrings(userData),
    ...getSchuldnerberatungsstelleStrings(userData),
    ...getAmtsgerichtRequirementStrings(userData),
    ...getInfoZumPKontoStrings(userData),
    ...getHasErhöhungStrings(userData),
    ...getRenteStrings(userData),
    ...getPflegegeldStrings(userData),
    ...getBescheinigungStrings(userData),
  }),
} satisfies Flow;
