name: "Parse Content to File"
description: "Parse all of Strapi content and put it into one file"
secrets:
  STRAPI_HOST:
    required: true
  STRAPI_ACCESS_KEY:
    required: true
  CONTENT_FILE_PATH:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install required python packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Execute create_content_file script
      shell: bash
      run: python create_content_file.py
      env:
        STRAPI_HOST: "${{ secrets.STRAPI_HOST }}"
        STRAPI_ACCESS_KEY: "${{ secrets.STRAPI_ACCESS_KEY }}"
        CONTENT_FILE_PATH: "${{ secrets.CONTENT_FILE_PATH }}"
