name: "Parse Content to File"
description: "Parse all of Strapi content and put it into one file"
inputs:
  STRAPI_API:
    description: "Strapi api url"
    required: true
  STRAPI_ACCESS_KEY:
    description: "API access key"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install required python packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Execute create_content_file script
      shell: bash
      run: python .github/actions/parse-content-to-file/create_content_file.py
      env:
        STRAPI_API: "${{ inputs.STRAPI_API }}"
        STRAPI_ACCESS_KEY: "${{ inputs.STRAPI_ACCESS_KEY }}"
        CONTENT_FILE_PATH: content.json
