import type { TestCases } from "~/domains/__test__/TestCases";
import { machine } from "./testMachine";
import { type KontopfaendungWegweiserUserData } from "../userData";

const cases = [
  [{}, ["/start", "/kontopfaendung", "/ergebnis/keine-kontopfaendung"]],
  [
    { hasKontopfaendung: "ja" },
    ["/start", "/kontopfaendung", "/ergebnis/keine-kontopfaendung"],
  ],
  [
    { hasKontopfaendung: "ja", hasPKonto: "ja" },
    ["/kontopfaendung", "/p-konto", "/zwischenseite-unterhalt"],
  ],
  [
    { hasKontopfaendung: "ja", hasPKonto: "nein" },
    ["/kontopfaendung", "/p-konto", "/zwischenseite-unterhalt"],
  ],
  [
    { hasKontopfaendung: "ja", hasPKonto: "nichtAktiv" },
    [
      "/kontopfaendung",
      "/p-konto",
      "/p-konto-probleme",
      "/zwischenseite-unterhalt",
    ],
  ],
  [
    { hasKontopfaendung: "ja", hasPKonto: "nichtEingerichtet" },
    [
      "/kontopfaendung",
      "/p-konto",
      "/p-konto-probleme",
      "/zwischenseite-unterhalt",
    ],
  ],
  [
    {},
    [
      "/zwischenseite-unterhalt",
      "/kinder",
      "/partner",
      "/zwischenseite-einkuenfte",
    ],
  ],
  [{ hasKinder: "no" }, ["/kinder", "/partner"]],
  [
    { hasKinder: "yes", kinderWohnenZusammen: "ja" },
    ["/kinder", "/kinder-wohnen-zusammen", "/partner"],
  ],
  [
    { hasKinder: "yes", kinderWohnenZusammen: "nein" },
    ["/kinder", "/kinder-wohnen-zusammen", "/kinder-unterhalt", "/partner"],
  ],
  [
    { hasKinder: "yes", kinderWohnenZusammen: "teilweise" },
    ["/kinder", "/kinder-wohnen-zusammen", "/kinder-unterhalt", "/partner"],
  ],
  [{ verheiratet: "nein" }, ["/partner", "/zwischenseite-einkuenfte"]],
  [{ verheiratet: "verwitwet" }, ["/partner", "/zwischenseite-einkuenfte"]],
  [
    { verheiratet: "geschieden" },
    ["/partner", "/partner-unterhalt", "/zwischenseite-einkuenfte"],
  ],
  [
    { verheiratet: "ja", partnerWohnenZusammen: "no" },
    [
      "/partner",
      "/partner-wohnen-zusammen",
      "/partner-unterhalt",
      "/zwischenseite-einkuenfte",
    ],
  ],
  [
    { verheiratet: "ja", partnerWohnenZusammen: "yes" },
    ["/partner", "/partner-wohnen-zusammen", "/zwischenseite-einkuenfte"],
  ],
  [
    { hasArbeit: "no", hasSozialleistungen: "nein" },
    ["/arbeit", "/sozialleistungen"],
  ],
  [
    { hasArbeit: "yes", nachzahlungArbeitgeber: "yes" },
    [
      "/arbeit-art",
      "/nachzahlung-arbeitgeber",
      "/hoehe-nachzahlung-arbeitgeber",
      "/einmalzahlung-arbeitgeber",
      "/sozialleistungen",
    ],
  ],
  [
    { hasArbeit: "yes", nachzahlungArbeitgeber: "no" },
    [
      "/arbeit-art",
      "/nachzahlung-arbeitgeber",
      "/einmalzahlung-arbeitgeber",
      "/sozialleistungen",
    ],
  ],
  [
    { hasArbeit: "yes", arbeitArt: { selbstaendig: "on", angestellt: "off" } },
    ["/arbeit", "/arbeit-art", "/sozialleistungen"],
  ],
  [
    { hasArbeit: "yes", arbeitArt: { selbstaendig: "off", angestellt: "off" } },
    ["/arbeit", "/arbeit-art", "/sozialleistungen"],
  ],
  [
    { hasArbeit: "yes", arbeitArt: { selbstaendig: "off", angestellt: "on" } },
    ["/arbeit", "/arbeit-art", "/nachzahlung-arbeitgeber"],
  ],
  [
    { hasArbeit: "yes", arbeitArt: { selbstaendig: "on", angestellt: "on" } },
    ["/arbeit", "/arbeit-art", "/nachzahlung-arbeitgeber"],
  ],
  [
    { hasKinder: "yes", hasKindergeld: "yes" },
    ["/kindergeld", "/kindergeld-nachzahlung"],
  ],
  [
    {
      hasSozialleistungen: "grundsicherungSozialhilfe",
      hasSozialleistungNachzahlung: "yes",
      hasSozialleistungenEinmalzahlung: "no",
    },
    [
      "/sozialleistungen",
      "/sozialleistung-nachzahlung",
      "/sozialleistungen-einmalzahlung",
      "/wohngeld",
    ],
  ],

  [{ hasWohngeld: "no" }, ["/wohngeld", "/pflegegeld"]],
  [
    { hasWohngeld: "yes", wohngeldEmpfaenger: "selbst" },
    [
      "/wohngeld",
      "/wohngeld-empfaenger",
      "/wohngeld-nachzahlung",
      "/pflegegeld",
    ],
  ],
  [
    { hasWohngeld: "yes", wohngeldEmpfaenger: "fremd" },
    ["/wohngeld", "/wohngeld-empfaenger", "/pflegegeld"],
  ],
  [
    { hasPflegegeld: "yes" },
    ["/pflegegeld", "/rente", "/ergebnis/naechste-schritte"],
  ],
  [
    {
      hasSozialleistungen: "nein",
      hasKindergeld: "no",
      hasWohngeld: "no",
      hasPflegegeld: "no",
      hasRente: "no",
    },
    [
      "/sozialleistungen",
      "/wohngeld",
      "/pflegegeld",
      "/rente",
      "/ergebnis/naechste-schritte",
    ],
  ],
  [
    {
      hasSozialleistungen: "buergergeld",
      hasSozialleistungNachzahlung: "yes",
      hasSozialleistungenEinmalzahlung: "yes",
    },
    [
      "/sozialleistungen",
      "/sozialleistung-nachzahlung",
      "/sozialleistungen-einmalzahlung",
    ],
  ],
  [
    {
      hasKontopfaendung: "ja",
      hasPKonto: "nichtEingerichtet",
      pfaendungUnterhalt: "yes",
      hasKinder: "no",
      verheiratet: "nein",
      hasArbeit: "no",
      nachzahlungArbeitgeber: "yes",
      hasSozialleistungen: "nein",
      hasKindergeld: "no",
      hasWohngeld: "no",
      hasPflegegeld: "no",
      hasRente: "no",
    },
    [
      "/start",
      "/kontopfaendung",
      "/p-konto",
      "/p-konto-probleme",
      "/zwischenseite-unterhalt",
      "/kinder",
      "/partner",
      "/zwischenseite-einkuenfte",
      "/arbeit",
      "/sozialleistungen",
      "/wohngeld",
      "/pflegegeld",
      "/rente",
      "/ergebnis/naechste-schritte",
    ],
  ],
  [
    {
      hasKontopfaendung: "ja",
      hasPKonto: "nichtEingerichtet",
      pfaendungUnterhalt: "yes",
      hasKinder: "yes",
      kinderWohnenZusammen: "nein",
      kinderUnterhalt: "no",
      verheiratet: "nein",
      hasArbeit: "yes",
      nachzahlungArbeitgeber: "yes",
      hasSozialleistungen: "nein",
      hasKindergeld: "no",
      hasWohngeld: "no",
      hasPflegegeld: "no",
      hasRente: "no",
    },
    [
      "/start",
      "/kontopfaendung",
      "/p-konto",
      "/p-konto-probleme",
      "/zwischenseite-unterhalt",
      "/kinder",
      "/kinder-wohnen-zusammen",
      "/kinder-unterhalt",
      "/partner",
      "/zwischenseite-einkuenfte",
      "/arbeit",
      "/arbeit-art",
      "/nachzahlung-arbeitgeber",
      "/hoehe-nachzahlung-arbeitgeber",
      "/einmalzahlung-arbeitgeber",
      "/sozialleistungen",
      "/kindergeld",
      "/wohngeld",
      "/pflegegeld",
      "/rente",
      "/ergebnis/naechste-schritte",
    ],
  ],
  [
    {
      hasKontopfaendung: "ja",
      hasPKonto: "ja",
      pfaendungUnterhalt: "yes",
      hasKinder: "yes",
      kinderWohnenZusammen: "ja",
      verheiratet: "ja",
      partnerWohnenZusammen: "yes",
      hasArbeit: "yes",
      nachzahlungArbeitgeber: "no",
      hasSozialleistungen: "nein",
      hasKindergeld: "yes",
      hasKindergeldNachzahlung: "yes",
      hasWohngeld: "no",
      hasPflegegeld: "no",
      hasRente: "no",
    },
    [
      "/start",
      "/kontopfaendung",
      "/p-konto",
      "/zwischenseite-unterhalt",
      "/kinder",
      "/kinder-wohnen-zusammen",
      "/partner",
      "/partner-wohnen-zusammen",
      "/zwischenseite-einkuenfte",
      "/arbeit",
      "/arbeit-art",
      "/nachzahlung-arbeitgeber",
      "/einmalzahlung-arbeitgeber",
      "/sozialleistungen",
      "/kindergeld",
      "/kindergeld-nachzahlung",
      "/wohngeld",
      "/pflegegeld",
      "/rente",
      "/ergebnis/naechste-schritte",
    ],
  ],
] as const satisfies TestCases<KontopfaendungWegweiserUserData>;

export const testCasesKontopfaendungWegweiser = { machine, cases };
