import { compileFlow } from "~/services/flow/newFlowEngine/compileFlow";
import { geldEinklagenFormularPages } from "./pages";
import { objectKeysNonEmpty } from "~/util/objectKeysNonEmpty";

export const geldEinklagenFlowConfig = compileFlow({
  pages: geldEinklagenFormularPages,
  initialStep: "introAnwaltschaft",
  transitions: {
    introAnwaltschaft: [
      {
        guard: (context) => context.anwaltschaft === "yes",
        target: "introVoraussetzungenAnwaltschaft",
      },
      { target: "introVoraussetzungen" },
    ],
    introVoraussetzungenAnwaltschaft: "introStart",
    introVoraussetzungen: "introStart",
    introStart: [{
      guard: (context) => objectKeysNonEmpty(context, ["anwaltschaft"]),
      target: "forderungWas",
    }],
    forderungWas: [
      {
        guard: (context) => context.forderung === "etwasAnderes",
        target: "forderungErrorEtwasAnderes",
      },
      {
        target: "sachgebietInfo",
        guard: (context) => objectKeysNonEmpty(context, ["forderung"]),
      },
    ],
    forderungErrorEtwasAnderes: null,
    sachgebietInfo: null,
    sachgebietAusgeschlossen: null,
    sachgebietBesondere: null,
    sachgebietMietePachtVertrag: null,
    sachgebietMietePachtRaum: null,
    sachgebietVersicherungVertrag: null,
    sachgebietVersicherungVersicherungsnehmer: null,
    sachgebietReiseArt: null,
    sachgebietReiseInfoFlug: null,
    sachgebietVerkehrsunfallStrassenverkehr: null,
    klagendePersonFuerWen: null,
    klagendePersonErrorAbbruch: null,
    klagendePersonVerbraucher: null,
    klagendePersonKaufmann: null,
    klagendePersonVertrag: null,
    klagendePersonHaustuergeschaeft: null,
    beklagtePersonGegenWen: null,
    beklagtePersonGeldVerdienen: null,
    beklagtePersonKaufmann: null,
    beklagtePersonGerichtsstandsvereinbarung: null,
    gerichtSuchenPostleitzahlBeklagtePerson: null,
    gerichtSuchenStrasseNummerBeklagtePerson: null,
    gerichtSuchenPostleitzahlWohnraum: null,
    gerichtSuchenPostleitzahlKlagendePerson: null,
    gerichtSuchenPostleitzahlUnerlaubtePerson: null,
    gerichtSuchenPostleitzahlVerkehrsunfall: null,
    gerichtSuchenPostleitzahlGerichtsstandsvereinbarung: null,
    gerichtSuchenStrasseNummer: null,
    zustaendigesGerichtPilotGericht: null,
    zustaendigesGerichtPilotGerichtAuswahl: null,
    zustaendigesGerichtGerichtAbbruch: null,
    klageErstellenIntroStart: null,
    streitWertKostenGerichtskostenvorschuss: null,
    streitwertKostenWeitereKosten: null,
    klagendePersonKontaktdaten: null,
    klagendePersonAnwaltschaft: null,
    beklagtePersonMenschen: null,
    beklagtePersonOrganisation: null,
    forderungGesamtbetrag: null,
    sachverhaltBegruendung: null,
    beweiseAngebot: null,
    beweiseBeschreibung: null,
    prozessfuehrungAnwaltskosten: null,
    prozessfuehrungProzesszinsen: null,
    prozessfuehrungStreitbeilegung: null,
    prozessfuehrungStreitbeilegungGruende: null,
    prozessfuehrungMuendlicheVerhandlung: null,
    prozessfuehrungVideoVerhandlung: null,
    prozessfuehrungVersaeumnisurteil: null,
    prozessfuehrungZahlungNachKlageeinreichung: null,
    rechtlicherZusatzWeitereAntraege: null,
    rechtlicherZusatzRechtlicheWuerdigung: null,
    zusammenfassungUebersicht: null
  },
});