import { useState, useRef } from "react";
import Button from "~/components/common/Button";
import { useShouldPrint } from "~/components/hooks/useShouldPrint";
import type { SummaryItem } from "~/services/summary/types";
import SummarySection from "./SummarySection";

type CollapsibleProps = {
  items: SummaryItem[];
  showGlobalControls?: boolean;
  expandAllText?: string;
  collapseAllText?: string;
};

const AutoGeneratedSummary = ({
  items,
  showGlobalControls = true,
  expandAllText = "Alle einblenden",
  collapseAllText = "Alle ausblenden",
}: Readonly<CollapsibleProps>) => {
  const shouldPrint = useShouldPrint();
  const itemsRef = useRef<HTMLDetailsElement[]>([]);

  const [openSections, setOpenSections] = useState<Set<string | number>>(() => {
    // Open first section by default
    if (items.length > 0) {
      return new Set([items[0].id ?? 0]);
    }
    return new Set();
  });

  const allOpen = openSections.size === items.length;
  const noneOpen = openSections.size === 0;

  const expandAll = () => {
    for (const item of itemsRef.current) {
      if (item) item.open = true;
    }
    setOpenSections(new Set(items.map((item, index) => item.id ?? index)));
  };

  const collapseAll = () => {
    for (const item of itemsRef.current) {
      if (item) item.open = false;
    }
    setOpenSections(new Set());
  };

  const handleSectionToggle = (itemId: string | number, isOpen: boolean) => {
    const newOpenSections = new Set(openSections);
    if (isOpen) {
      newOpenSections.add(itemId);
    } else {
      newOpenSections.delete(itemId);
    }
    setOpenSections(newOpenSections);
  };

  if (items.length === 0) {
    return null;
  }

  return (
    <div>
      {showGlobalControls && (
        <div className="flex gap-8 mb-16">
          <Button
            look="tertiary"
            size="small"
            onClick={expandAll}
            disabled={allOpen}
            text={expandAllText}
          />
          <Button
            look="tertiary"
            size="small"
            onClick={collapseAll}
            disabled={noneOpen}
            text={collapseAllText}
          />
        </div>
      )}

      <div>
        {items.map((item, index) => {
          const itemId = item.id ?? index;
          const startOpened = shouldPrint || openSections.has(itemId);

          return (
            <SummarySection
              key={itemId}
              item={item}
              itemId={itemId}
              startOpened={startOpened}
              onToggle={handleSectionToggle}
            />
          );
        })}
      </div>
    </div>
  );
};

export default AutoGeneratedSummary;
