name: "Test Production Text"
description: "Check that a specific text is displayed on the production system"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Execute text-test script
      shell: bash
      run: sh .github/actions/production-text-test/test-text.sh
