import { type TestCases } from "~/domains/__test__/TestCases";
import { type GeldEinklagenFormularUserData } from "../../userData";

const ZIP_CODE_PILOT_COURT = "10823";

const baseContext: GeldEinklagenFormularUserData = {
  anwaltschaft: "no",
  forderung: "maximal10000",
  ausgeschlossen: "yes",
  fuerWenKlagen: "selbst",
  sachgebiet: "miete",
  gegenWenBeklagen: "person",
  mietePachtVertrag: "yes",
  mietePachtRaum: "yes",
  postleitzahlSecondary: ZIP_CODE_PILOT_COURT,
  beklagteStrasseHausnummer: "beklagteStrasseHausnummer",
  beklagtePlz: ZIP_CODE_PILOT_COURT,
  beklagteOrt: "beklagteOrt",
  klagendePersonAnrede: "none",
  klagendePersonTitle: "none",
  klagendePersonVorname: "klagendePersonVorname",
  klagendePersonNachname: "klagendePersonNachname",
  klagendePersonStrasseHausnummer: "klagendePersonStrasseHausnummer",
  klagendePersonPlz: ZIP_CODE_PILOT_COURT,
  klagendePersonOrt: "klagendePersonOrt",
  forderungGesamtbetrag: "100.00",
  sachverhaltBegruendung: "some reason",
  pageData: {
    subflowDoneStates: {
      "/klage-erstellen/klagende-person": true,
      "/klage-erstellen/beklagte-person": true,
      "/klage-erstellen/forderung": true,
      "/klage-erstellen/sachverhalt": true,
    },
  },
};

export const testCasesKlagenErstellenInitial = [
  [
    {
      ...baseContext,
      beklagteAnrede: "none",
      beklagteTitle: "none",
      beklagteVorname: "beklagteVorname",
      beklagteNachname: "beklagteNachname",
      beweiseAngebot: "yes",
      beweiseBeschreibung: "some description",
    },
    [
      "/klage-erstellen/intro/start",
      "/klage-erstellen/streitwert-kosten/gerichtskostenvorschuss",
      "/klage-erstellen/streitwert-kosten/weitere-kosten",
      "/klage-erstellen/klagende-person/kontaktdaten",
      "/klage-erstellen/beklagte-person/mensch",
      "/klage-erstellen/forderung/gesamtbetrag",
      "/klage-erstellen/sachverhalt/begruendung",
      "/klage-erstellen/beweise/angebot",
      "/klage-erstellen/beweise/beschreibung",
      "/klage-erstellen/prozessfuehrung/anwaltskosten",
      "/klage-erstellen/prozessfuehrung/prozesszinsen",
    ],
  ],
  [
    {
      ...baseContext,
      gegenWenBeklagen: "organisation",
      beklagteNameOrganisation: "beklagteNameOrganisation",
      beklagteGesetzlichenVertretungVorname:
        "beklagteGesetzlichenVertretungVorname",
      beklagteGesetzlichenVertretungNachname:
        "beklagteGesetzlichenVertretungNachname",
      beklagteGesetzlichenVertretungAnrede: "herr",
      beklagteGesetzlichenVertretungTitle: "dr",
      beweiseAngebot: "yes",
      beweiseBeschreibung: "some description",
    },
    [
      "/klage-erstellen/intro/start",
      "/klage-erstellen/streitwert-kosten/gerichtskostenvorschuss",
      "/klage-erstellen/streitwert-kosten/weitere-kosten",
      "/klage-erstellen/klagende-person/kontaktdaten",
      "/klage-erstellen/beklagte-person/organisation",
      "/klage-erstellen/forderung/gesamtbetrag",
      "/klage-erstellen/sachverhalt/begruendung",
      "/klage-erstellen/beweise/angebot",
      "/klage-erstellen/beweise/beschreibung",
      "/klage-erstellen/prozessfuehrung/anwaltskosten",
      "/klage-erstellen/prozessfuehrung/prozesszinsen",
    ],
  ],
  [
    {
      ...baseContext,
      beklagteAnrede: "none",
      beklagteTitle: "none",
      beklagteVorname: "beklagteVorname",
      beklagteNachname: "beklagteNachname",
      beweiseAngebot: "no",
    },
    [
      "/klage-erstellen/intro/start",
      "/klage-erstellen/streitwert-kosten/gerichtskostenvorschuss",
      "/klage-erstellen/streitwert-kosten/weitere-kosten",
      "/klage-erstellen/klagende-person/kontaktdaten",
      "/klage-erstellen/beklagte-person/mensch",
      "/klage-erstellen/forderung/gesamtbetrag",
      "/klage-erstellen/sachverhalt/begruendung",
      "/klage-erstellen/beweise/angebot",
      "/klage-erstellen/prozessfuehrung/anwaltskosten",
      "/klage-erstellen/prozessfuehrung/prozesszinsen",
    ],
  ],
  [
    {
      ...baseContext,
      gegenWenBeklagen: "organisation",
      beklagteNameOrganisation: "beklagteNameOrganisation",
      beklagteGesetzlichenVertretungVorname:
        "beklagteGesetzlichenVertretungVorname",
      beklagteGesetzlichenVertretungNachname:
        "beklagteGesetzlichenVertretungNachname",
      beklagteGesetzlichenVertretungAnrede: "herr",
      beklagteGesetzlichenVertretungTitle: "dr",
      beweiseAngebot: "no",
    },
    [
      "/klage-erstellen/intro/start",
      "/klage-erstellen/streitwert-kosten/gerichtskostenvorschuss",
      "/klage-erstellen/streitwert-kosten/weitere-kosten",
      "/klage-erstellen/klagende-person/kontaktdaten",
      "/klage-erstellen/beklagte-person/organisation",
      "/klage-erstellen/forderung/gesamtbetrag",
      "/klage-erstellen/sachverhalt/begruendung",
      "/klage-erstellen/beweise/angebot",
      "/klage-erstellen/prozessfuehrung/anwaltskosten",
      "/klage-erstellen/prozessfuehrung/prozesszinsen",
    ],
  ],
  [
    {
      ...baseContext,
      anwaltschaft: "yes",
      gegenWenBeklagen: "organisation",
      klagendePersonAnwaltschaftStrasseHausnummer:
        "klagendePersonAnwaltschaftStrasseHausnummer",
      klagendePersonAnwaltschaftPlz: ZIP_CODE_PILOT_COURT,
      klagendePersonAnwaltschaftOrt: "klagendePersonAnwaltschaftOrt",
      klagendePersonAnwaltschaftAnrede: "none",
      klagendePersonAnwaltschaftVorname: "klagendePersonAnwaltschaftVorname",
      klagendePersonAnwaltschaftNachname: "klagendePersonAnwaltschaftNachname",
      klagendePersonAnwaltschaftTitle: "none",
      beklagteNameOrganisation: "beklagteNameOrganisation",
      beklagteGesetzlichenVertretungVorname:
        "beklagteGesetzlichenVertretungVorname",
      beklagteGesetzlichenVertretungNachname:
        "beklagteGesetzlichenVertretungNachname",
      beklagteGesetzlichenVertretungAnrede: "herr",
      beklagteGesetzlichenVertretungTitle: "dr",
      beweiseAngebot: "no",
    },
    [
      "/klage-erstellen/intro/start",
      "/klage-erstellen/streitwert-kosten/gerichtskostenvorschuss",
      "/klage-erstellen/streitwert-kosten/weitere-kosten",
      "/klage-erstellen/klagende-person/kontaktdaten-anwaltschaft",
      "/klage-erstellen/klagende-person/kontaktdaten",
      "/klage-erstellen/beklagte-person/organisation",
      "/klage-erstellen/forderung/gesamtbetrag",
      "/klage-erstellen/sachverhalt/begruendung",
      "/klage-erstellen/beweise/angebot",
      "/klage-erstellen/prozessfuehrung/anwaltskosten",
      "/klage-erstellen/prozessfuehrung/prozesszinsen",
    ],
  ],
] as const satisfies TestCases<GeldEinklagenFormularUserData>;
