import { type BeratungshilfeFormularUserData } from "~/domains/beratungshilfe/formular/userData";

export const happyPathData: BeratungshilfeFormularUserData = {
  rechtsschutzversicherung: "no",
  wurdeVerklagt: "no",
  klageEingereicht: "no",
  beratungshilfeBeantragt: "no",
  eigeninitiativeGrundvorraussetzung: "no",
  anwaltskanzlei: "no",
  bereich: "authorities",
  beschreibung: "sdfsdf",
  staatlicheLeistungen: "keine",
  erwerbstaetig: "no",
  berufsituation: "no",
  weitereseinkommen: {
    unterhaltszahlungen: "off",
    arbeitlosengeld: "off",
    wohngeld: "off",
    kindergeld: "off",
    bafoeg: "off",
    krankengeld: "off",
    rente: "off",
    elterngeld: "off",
    insolvenzgeld: "off",
    ueberbrueckungsgeld: "off",
    others: "on",
  },
  einkommen: "4,00",
  partnerschaft: "no",
  hasKinder: "yes",
  hasBankkonto: "no",
  hasKraftfahrzeug: "no",
  hasGeldanlage: "no",
  hasGrundeigentum: "no",
  hasWertsache: "no",
  kinder: [
    {
      vorname: "Kind 1",
      nachname: "Nachname 1",
      geburtsdatum: "12.12.1212",
      wohnortBeiAntragsteller: "yes",
      eigeneEinnahmen: "yes",
      einnahmen: "10",
    },
    {
      vorname: "Kind 2",
      nachname: "Nachname 2",
      geburtsdatum: "11.12.1212",
      wohnortBeiAntragsteller: "yes",
      eigeneEinnahmen: "yes",
      einnahmen: "10",
    },
  ],
};
