name: "Cached Checkout & Install"
description: "Checks out repository, downloads node, caches node_modules and installs project"
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: "package.json"
        cache: "pnpm"
    - name: Grab node version
      run: echo "NODE_VERSION=$(node --version)" >> $GITHUB_ENV
      shell: bash
    - name: Perform a clean install of node dependencies
      run: pnpm i
      shell: bash
