import { render, fireEvent } from "@testing-library/react";
import { describe, it, vi, expect } from "vitest";
import AutoGeneratedSummary from "../AutoGeneratedSummary";
import type { SummaryItem } from "~/services/summary/types";

vi.mock("~/components/hooks/useShouldPrint", () => ({
  useShouldPrint: vi.fn(() => false),
}));

vi.mock("~/components/common/StandaloneLink", () => ({
  StandaloneLink: vi.fn(({ url, text }) => <a href={url}>{text}</a>),
}));

describe("AutoGeneratedSummary", () => {
  const mockItems: SummaryItem[] = [
    {
      id: "section1",
      title: "Personal Data",
      fields: [
        {
          id: "field1",
          question: "What is your name?",
          answer: "John Doe",
        },
      ],
    },
    {
      id: "section2",
      title: "Financial Data",
      fields: [
        {
          id: "field2",
          question: "What is your income?",
          answer: "50000",
        },
      ],
    },
  ];

  it("should render nothing when no items provided", () => {
    const { container } = render(<AutoGeneratedSummary items={[]} />);
    expect(container.firstChild).toBeNull();
  });

  it("should render all summary sections", () => {
    const { getByText } = render(<AutoGeneratedSummary items={mockItems} />);

    expect(getByText("Personal Data")).toBeInTheDocument();
    expect(getByText("Financial Data")).toBeInTheDocument();
  });

  it("should open first section by default", () => {
    const { container } = render(<AutoGeneratedSummary items={mockItems} />);

    const details = container.querySelectorAll("details");
    expect(details[0]).toHaveAttribute("open");
    expect(details[1]).not.toHaveAttribute("open");
  });

  it("should render control buttons when showGlobalControls is true", () => {
    const { getByText } = render(
      <AutoGeneratedSummary items={mockItems} showGlobalControls={true} />,
    );

    expect(getByText("Alle einblenden")).toBeInTheDocument();
    expect(getByText("Alle ausblenden")).toBeInTheDocument();
  });

  it("should not render control buttons when showGlobalControls is false", () => {
    const { queryByText } = render(
      <AutoGeneratedSummary items={mockItems} showGlobalControls={false} />,
    );

    expect(queryByText("Alle einblenden")).not.toBeInTheDocument();
    expect(queryByText("Alle ausblenden")).not.toBeInTheDocument();
  });

  it("should expand all sections when expand all button is clicked", () => {
    const { getByText, container } = render(
      <AutoGeneratedSummary items={mockItems} />,
    );

    const expandButton = getByText("Alle einblenden");
    fireEvent.click(expandButton);

    const details = container.querySelectorAll("details");
    expect(details[0]).toHaveAttribute("open");
    expect(details[1]).toHaveAttribute("open");
  });
});
