import { render, fireEvent } from "@testing-library/react";
import { describe, it, vi, expect } from "vitest";
import AutoGeneratedSummary from "~/components/content/autoGeneratedSummary/AutoGeneratedSummary";
import type { SummaryItem } from "~/services/summary/types";
import { useJsAvailable } from "~/components/hooks/useJsAvailable";
import { userEvent } from "storybook/test";
import { translations } from "~/services/translations/translations";

vi.mock("~/components/hooks/useShouldPrint", () => ({
  useShouldPrint: vi.fn(() => false),
}));

vi.mock("~/components/common/StandaloneLink", () => ({
  StandaloneLink: vi.fn(({ url, text }) => <a href={url}>{text}</a>),
}));

vi.mock("~/components/hooks/useJsAvailable");

beforeEach(() => {
  vi.mocked(useJsAvailable).mockReturnValue(true);
});
const mockItems: SummaryItem[] = [
  {
    id: "section1",
    title: "Personal Data",
    fields: [
      {
        id: "field1",
        question: "What is your name?",
        answer: "John Doe",
      },
    ],
  },
  {
    id: "section2",
    title: "Financial Data",
    fields: [
      {
        id: "field2",
        question: "What is your income?",
        answer: "50000",
      },
    ],
  },
];
describe("AutoGeneratedSummary", () => {
  it("should render nothing when no items provided", () => {
    const { container } = render(<AutoGeneratedSummary items={[]} />);
    expect(container.firstChild).toBeNull();
  });

  it("should render all summary sections", () => {
    const { getByText } = render(<AutoGeneratedSummary items={mockItems} />);

    expect(getByText("Personal Data")).toBeInTheDocument();
    expect(getByText("Financial Data")).toBeInTheDocument();
  });

  it("should open first section by default", () => {
    const { container } = render(<AutoGeneratedSummary items={mockItems} />);

    const details = container.querySelectorAll("details");
    expect(details[0]).toHaveAttribute("open");
    expect(details[1]).not.toHaveAttribute("open");
  });

  it("should render control buttons when showGlobalControls is true", () => {
    const { getByText } = render(
      <AutoGeneratedSummary items={mockItems} showGlobalControls={true} />,
    );

    expect(getByText("Alle einblenden")).toBeInTheDocument();
    expect(getByText("Alle ausblenden")).toBeInTheDocument();
  });

  it("should not render control buttons when showGlobalControls is false", () => {
    const { queryByText } = render(
      <AutoGeneratedSummary items={mockItems} showGlobalControls={false} />,
    );

    expect(queryByText("Alle einblenden")).not.toBeInTheDocument();
    expect(queryByText("Alle ausblenden")).not.toBeInTheDocument();
  });

  it("should not render control buttons when jsAvailable is false", () => {
    vi.mocked(useJsAvailable).mockReturnValue(false);
    const { queryByText } = render(<AutoGeneratedSummary items={mockItems} />);

    expect(queryByText("Alle einblenden")).not.toBeInTheDocument();
    expect(queryByText("Alle ausblenden")).not.toBeInTheDocument();
  });

  it("should expand all sections when expand all button is clicked", () => {
    const { getByText, container } = render(
      <AutoGeneratedSummary items={mockItems} />,
    );

    const expandButton = getByText("Alle einblenden");
    fireEvent.click(expandButton);

    const details = container.querySelectorAll("details");
    expect(details[0]).toHaveAttribute("open");
    expect(details[1]).toHaveAttribute("open");
  });
});

describe("AutoGeneratedSummary accessibility", () => {
  it("should render buttons with correct accessible names", () => {
    const { getByRole } = render(<AutoGeneratedSummary items={mockItems} />);

    const expandButton = getByRole("button", {
      name: translations.autogeneratedSummary.expandAllText.de,
    });

    const collapseButton = getByRole("button", {
      name: translations.autogeneratedSummary.collapseAllText.de,
    });

    expect(expandButton).toBeInTheDocument();
    expect(collapseButton).toBeInTheDocument();
  });

  it("should mark expand button as aria-disabled when all sections are open", async () => {
    const { getByRole, container } = render(
      <AutoGeneratedSummary items={mockItems} showGlobalControls={true} />,
    );

    const expandButton = getByRole("button", {
      name: translations.autogeneratedSummary.expandAllText.de,
    });

    await userEvent.click(expandButton);

    const details = container.querySelectorAll("details");
    expect(details[0]).toHaveAttribute("open");
    expect(details[1]).toHaveAttribute("open");
    expect(expandButton).toHaveAttribute("aria-disabled", "true");
  });

  it("should update aria-label of expand button when all sections are open", async () => {
    const { getByRole, container } = render(
      <AutoGeneratedSummary items={mockItems} showGlobalControls={true} />,
    );

    const expandButton = getByRole("button", {
      name: translations.autogeneratedSummary.expandAllText.de,
    });

    await userEvent.click(expandButton);

    const details = container.querySelectorAll("details");
    expect(details[0]).toHaveAttribute("open");
    expect(details[1]).toHaveAttribute("open");
    expect(expandButton).toHaveAttribute(
      "aria-label",
      `${translations.autogeneratedSummary.expandAllText.de}, ${translations.autogeneratedSummary.expandAllAriaLabelText.de}`,
    );
  });

  it("should not not expand sections when all sections are already expanded", async () => {
    const { getByRole, container } = render(
      <AutoGeneratedSummary items={mockItems} showGlobalControls={true} />,
    );

    const expandButton = getByRole("button", {
      name: translations.autogeneratedSummary.expandAllText.de,
    });

    await userEvent.click(expandButton);

    const details = container.querySelectorAll("details");
    expect(details[0]).toHaveAttribute("open");
    expect(details[1]).toHaveAttribute("open");
    expect(expandButton).toHaveAttribute("aria-disabled", "true");

    await userEvent.click(expandButton);

    expect(details[0]).toHaveAttribute("open");
    expect(details[1]).toHaveAttribute("open");
  });

  it("should update the state after clicking expand all", async () => {
    const { getByRole, container } = render(
      <AutoGeneratedSummary items={mockItems} showGlobalControls={true} />,
    );

    const expandButton = getByRole("button", {
      name: translations.autogeneratedSummary.expandAllText.de,
    });

    await userEvent.click(expandButton);

    const details = container.querySelectorAll("details");
    expect(details[0]).toHaveAttribute("open");
    expect(details[1]).toHaveAttribute("open");
  });

  it("should update the state after clicking collapse all", async () => {
    const { getByRole, container } = render(
      <AutoGeneratedSummary items={mockItems} showGlobalControls={true} />,
    );

    const collapseButton = getByRole("button", {
      name: translations.autogeneratedSummary.collapseAllText.de,
    });

    await userEvent.click(collapseButton);

    const details = container.querySelectorAll("details");
    expect(details[0]).not.toHaveAttribute("open");
    expect(details[1]).not.toHaveAttribute("open");
  });
});
