import type { TestCases } from "~/domains/__test__/TestCases";
import type { FluggastrechteUserData } from "~/domains/fluggastrechte/formular/userData";
import { fluggesellschaftAddresse } from "./flugdatenMock";

const baseContext = {
  ...fluggesellschaftAddresse,
  bereich: "verspaetet",
  direktFlugnummer: "AB1234",
  buchungsNummer: "X36Q9C",
  direktAbflugsDatum: "01.05.2023",
  direktAbflugsZeit: "10:00",
  direktAnkunftsDatum: "02.05.2023",
  direktAnkunftsZeit: "10:00",
};

export const testCasesFluggastrechteFormularFlugdatenVerspaetet = [
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "no",
      tatsaechlicherFlug: "no",
      ersatzverbindungArt: "flug",
      ersatzFlugnummer: "BCA4321",
      ersatzFlugAnkunftsDatum: "10.03.2024",
      ersatzFlugAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/tatsaechlicher-flug",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/anderer-flug-ankunft",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "no",
      tatsaechlicherFlug: "no",
      ersatzverbindungArt: "etwasAnderes",
      andereErsatzverbindungAnkunftsDatum: "10.03.2024",
      andereErsatzverbindungAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/tatsaechlicher-flug",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/ersatzverbindung-beschreibung",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "no",
      tatsaechlicherFlug: "no",
      ersatzverbindungArt: "keineAnkunft",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/tatsaechlicher-flug",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "no",
      tatsaechlicherFlug: "yes",
      tatsaechlicherAnkunftsDatum: "10.03.2024",
      tatsaechlicherAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/tatsaechlicher-flug",
      "/flugdaten/tatsaechlicher-flug-ankunft",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "oneStop",
      verspaeteterFlugOneStop: "startAirportFirstZwischenstopp",
      anschlussFlugVerpasst: "yes",
      ersterZwischenstopp: "HAM",
      tatsaechlicherFlug: "no",
      ersatzverbindungArt: "flug",
      ersatzFlugnummer: "BCA4321",
      ersatzFlugAnkunftsDatum: "10.03.2024",
      ersatzFlugAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-1",
      "/flugdaten/verspaeteter-flug-1",
      "/flugdaten/anschluss-flug-verpasst",
      "/flugdaten/tatsaechlicher-flug",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/anderer-flug-ankunft",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "oneStop",
      verspaeteterFlugOneStop: "firstZwischenstoppEndAirport",
      ersterZwischenstopp: "HAM",
      tatsaechlicherFlug: "no",
      ersatzverbindungArt: "flug",
      ersatzFlugnummer: "BCA4321",
      ersatzFlugAnkunftsDatum: "10.03.2024",
      ersatzFlugAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-1",
      "/flugdaten/verspaeteter-flug-1",
      "/flugdaten/tatsaechlicher-flug",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/anderer-flug-ankunft",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "twoStop",
      verspaeteterFlugTwoStops: "startAirportFirstZwischenstopp",
      anschlussFlugVerpasst: "no",
      tatsaechlicherFlug: "no",
      ersatzverbindungArt: "flug",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-2",
      "/flugdaten/verspaeteter-flug-2",
      "/flugdaten/anschluss-flug-verpasst",
      "/flugdaten/tatsaechlicher-flug",
      "/flugdaten/ersatzverbindung-art",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "twoStop",
      verspaeteterFlugTwoStops: "firstAirportSecondZwischenstopp",
      anschlussFlugVerpasst: "no",
      tatsaechlicherFlug: "no",
      ersatzverbindungArt: "flug",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-2",
      "/flugdaten/verspaeteter-flug-2",
      "/flugdaten/anschluss-flug-verpasst",
      "/flugdaten/tatsaechlicher-flug",
      "/flugdaten/ersatzverbindung-art",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "twoStop",
      verspaeteterFlugTwoStops: "secondZwischenstoppEndAirport",
      anschlussFlugVerpasst: "no",
      tatsaechlicherFlug: "no",
      ersatzverbindungArt: "flug",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-2",
      "/flugdaten/verspaeteter-flug-2",
      "/flugdaten/tatsaechlicher-flug",
      "/flugdaten/ersatzverbindung-art",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "threeStop",
      verspaeteterFlugThreeStops: "startAirportFirstZwischenstopp",
      anschlussFlugVerpasst: "no",
      tatsaechlicherFlug: "no",
      ersatzverbindungArt: "flug",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-3",
      "/flugdaten/verspaeteter-flug-3",
      "/flugdaten/anschluss-flug-verpasst",
      "/flugdaten/tatsaechlicher-flug",
      "/flugdaten/ersatzverbindung-art",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "threeStop",
      verspaeteterFlugThreeStops: "firstAirportSecondZwischenstopp",
      anschlussFlugVerpasst: "no",
      tatsaechlicherFlug: "no",
      ersatzverbindungArt: "flug",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-3",
      "/flugdaten/verspaeteter-flug-3",
      "/flugdaten/anschluss-flug-verpasst",
      "/flugdaten/tatsaechlicher-flug",
      "/flugdaten/ersatzverbindung-art",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "threeStop",
      verspaeteterFlugThreeStops: "secondAirportThirdZwischenstopp",
      anschlussFlugVerpasst: "no",
      tatsaechlicherFlug: "no",
      ersatzverbindungArt: "flug",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-3",
      "/flugdaten/verspaeteter-flug-3",
      "/flugdaten/anschluss-flug-verpasst",
      "/flugdaten/tatsaechlicher-flug",
      "/flugdaten/ersatzverbindung-art",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "threeStop",
      verspaeteterFlugThreeStops: "thirdZwischenstoppEndAirport",
      tatsaechlicherFlug: "no",
      ersatzverbindungArt: "flug",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-3",
      "/flugdaten/verspaeteter-flug-3",
      "/flugdaten/tatsaechlicher-flug",
      "/flugdaten/ersatzverbindung-art",
    ],
  ],
] as const satisfies TestCases<FluggastrechteUserData>;
