import type { TestCases } from "~/domains/__test__/TestCases";
import type { FluggastrechteUserData } from "~/domains/fluggastrechte/formular/userData";
import { fluggesellschaftAddresse } from "./flugdatenMock";
import { daysFromToday } from "./mockedDate";

const baseContext = {
  ...fluggesellschaftAddresse,
  bereich: "nichtbefoerderung",
  direktFlugnummer: "AB1234",
  buchungsNummer: "X36Q9C",
  direktAbflugsDatum: daysFromToday(0),
  direktAbflugsZeit: "10:00",
  direktAnkunftsDatum: daysFromToday(0),
  direktAnkunftsZeit: "10:00",
};

export const testCasesFluggastrechteFormularFlugdatenNichtBefoerderung = [
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "no",
      ersatzverbindungArt: "flug",
      ersatzFlugnummer: "BCA4321",
      ersatzFlugAnkunftsDatum: daysFromToday(0),
      ersatzFlugAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/anderer-flug-ankunft",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "no",
      ersatzverbindungArt: "etwasAnderes",
      andereErsatzverbindungAnkunftsDatum: daysFromToday(0),
      andereErsatzverbindungAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/ersatzverbindung-beschreibung",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "no",
      ersatzverbindungArt: "keineAnkunft",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "oneStop",
      verspaeteterFlugOneStop: "startAirportFirstZwischenstopp",
      anschlussFlugVerpasst: "no",
      ersterZwischenstopp: "HAM",
      ersatzverbindungArt: "flug",
      ersatzFlugnummer: "BCA4321",
      ersatzFlugAnkunftsDatum: daysFromToday(0),
      ersatzFlugAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-1",
      "/flugdaten/verspaeteter-flug-1",
      "/flugdaten/anschluss-flug-verpasst",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/anderer-flug-ankunft",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "oneStop",
      verspaeteterFlugOneStop: "firstZwischenstoppEndAirport",
      ersterZwischenstopp: "HAM",
      ersatzverbindungArt: "flug",
      ersatzFlugnummer: "BCA4321",
      ersatzFlugAnkunftsDatum: daysFromToday(0),
      ersatzFlugAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-1",
      "/flugdaten/verspaeteter-flug-1",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/anderer-flug-ankunft",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "twoStop",
      verspaeteterFlugTwoStops: "firstAirportSecondZwischenstopp",
      anschlussFlugVerpasst: "no",
      ersterZwischenstopp: "HAM",
      zweiterZwischenstopp: "JFK",
      ersatzverbindungArt: "flug",
      ersatzFlugnummer: "BCA4321",
      ersatzFlugAnkunftsDatum: daysFromToday(0),
      ersatzFlugAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-2",
      "/flugdaten/verspaeteter-flug-2",
      "/flugdaten/anschluss-flug-verpasst",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/anderer-flug-ankunft",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "twoStop",
      verspaeteterFlugTwoStops: "secondZwischenstoppEndAirport",
      ersterZwischenstopp: "HAM",
      zweiterZwischenstopp: "JFK",
      ersatzverbindungArt: "flug",
      ersatzFlugnummer: "BCA4321",
      ersatzFlugAnkunftsDatum: daysFromToday(0),
      ersatzFlugAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-2",
      "/flugdaten/verspaeteter-flug-2",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/anderer-flug-ankunft",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "threeStop",
      verspaeteterFlugThreeStops: "startAirportFirstZwischenstopp",
      anschlussFlugVerpasst: "no",
      ersterZwischenstopp: "HAM",
      zweiterZwischenstopp: "BER",
      dritterZwischenstopp: "MUC",
      ersatzverbindungArt: "flug",
      ersatzFlugnummer: "BCA4321",
      ersatzFlugAnkunftsDatum: daysFromToday(0),
      ersatzFlugAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-3",
      "/flugdaten/verspaeteter-flug-3",
      "/flugdaten/anschluss-flug-verpasst",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/anderer-flug-ankunft",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "threeStop",
      verspaeteterFlugThreeStops: "firstAirportSecondZwischenstopp",
      anschlussFlugVerpasst: "no",
      ersterZwischenstopp: "HAM",
      zweiterZwischenstopp: "BER",
      dritterZwischenstopp: "MUC",
      ersatzverbindungArt: "flug",
      ersatzFlugnummer: "BCA4321",
      ersatzFlugAnkunftsDatum: daysFromToday(0),
      ersatzFlugAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-3",
      "/flugdaten/verspaeteter-flug-3",
      "/flugdaten/anschluss-flug-verpasst",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/anderer-flug-ankunft",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "threeStop",
      verspaeteterFlugThreeStops: "secondAirportThirdZwischenstopp",
      anschlussFlugVerpasst: "no",
      ersterZwischenstopp: "HAM",
      zweiterZwischenstopp: "BER",
      dritterZwischenstopp: "MUC",
      ersatzverbindungArt: "flug",
      ersatzFlugnummer: "BCA4321",
      ersatzFlugAnkunftsDatum: daysFromToday(0),
      ersatzFlugAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-3",
      "/flugdaten/verspaeteter-flug-3",
      "/flugdaten/anschluss-flug-verpasst",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/anderer-flug-ankunft",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
  [
    {
      ...baseContext,
      zwischenstoppAnzahl: "threeStop",
      verspaeteterFlugThreeStops: "thirdZwischenstoppEndAirport",
      ersterZwischenstopp: "HAM",
      zweiterZwischenstopp: "BER",
      dritterZwischenstopp: "MUC",
      ersatzverbindungArt: "flug",
      ersatzFlugnummer: "BCA4321",
      ersatzFlugAnkunftsDatum: daysFromToday(0),
      ersatzFlugAnkunftsZeit: "10:10",
      zusaetzlicheAngaben: "Zusätzliche Angaben zum Reiseverlauf",
    },
    [
      "/flugdaten/geplanter-flug",
      "/flugdaten/zwischenstopp-uebersicht-3",
      "/flugdaten/verspaeteter-flug-3",
      "/flugdaten/ersatzverbindung-art",
      "/flugdaten/anderer-flug-ankunft",
      "/flugdaten/zusaetzliche-angaben",
      "/persoenliche-daten/person/daten",
    ],
  ],
] as const satisfies TestCases<FluggastrechteUserData>;
