name: Audit

on:
  push:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.15.1"
          cache: "npm"
      - run: npm install && npm install -g @lhci/cli@0.11.x
      - run: |
          sudo apt-get update
          sudo apt-get install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2
      - uses: browser-actions/setup-chrome@v1
      - name: Configure Environment
        run: |-
          echo "CHROME_PATH=/opt/hostedtoolcache/chromium/latest/x64/chrome" >> $GITHUB_ENV

      - run: lhci autorun
