name: buildAppImage
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-push-app-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build app image
        run: docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --target app -f split.Dockerfile
      - name: Push app image
        run: docker push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: ./.github/actions/build-prod-image
        with:
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ github.repository }}-prod
          CONTENT_IMAGE: ${{ env.REGISTRY }}/${{ github.repository }}-content
          APP_IMAGE: ${{ env.REGISTRY }}/${{ github.repository }}-app
