name: CodeQuality
on:
  workflow_call:
    secrets:
      SENTRY_AUTH_TOKEN:
        required: false
      GERICHTSFINDER_ENCRYPTION_KEY:
        required: false

jobs:
  code-quality:
    strategy:
      matrix:
        cmd: ["format", "lint", "typecheck", "test:coverage"]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    name: pnpm run ${{ matrix.cmd }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/cached-checkout-install
      - run: pnpm run ${{ matrix.cmd }}
        env:
          SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
          GERICHTSFINDER_ENCRYPTION_KEY: "${{ secrets.GERICHTSFINDER_ENCRYPTION_KEY }}"
      - name: Upload coverage
        if: ${{ matrix.cmd == 'test:coverage' }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: coverage
          path: coverage/
          retention-days: 1
