name: PNPMChecks
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  code-quality:
    strategy:
      matrix:
        npmCMD: ["format", "lint", "typecheck", "test:coverage"]
    permissions:
      packages: read
    runs-on: ubuntu-latest
    name: pnpm run ${{ matrix.npmCMD }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/cached-checkout-install
      - run: pnpm run ${{ matrix.npmCMD }}
      - name: SonarCloud Scan
        if: ${{ github.actor != 'dependabot[bot]' && matrix.npmCMD == 'test:coverage' }}
        uses: SonarSource/sonarcloud-github-action@383f7e52eae3ab0510c3cb0e7d9d150bbaeab838 # v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
