import { useFormFlow } from "~/components/formFlowContext";
import SummaryOverviewBox from "./SummaryOverviewBox";
import SummaryOverviewBoxArray from "./SummaryOverviewBoxArray";
import { type SummaryOverviewBoxWrappedProps } from "./types";

const SummaryOverviewBoxWrapped = ({
  title,
  id,
  stepId,
  boxItems,
}: SummaryOverviewBoxWrappedProps) => {
  const { userData, validFlowPages } = useFormFlow();

  // Check if this is an auto-generated section (bypass validation)
  const isAutoGenerated = stepId.startsWith("auto-generated:");

  if (!isAutoGenerated && !validFlowPages[stepId]) {
    return null;
  }

  // For auto-generated sections, assume it's not an array page
  const isArrayPage = !isAutoGenerated && validFlowPages[stepId]?.isArrayPage;

  if (isArrayPage) {
    return (
      <SummaryOverviewBoxArray
        boxId={id}
        title={title}
        boxItems={boxItems}
        stepId={stepId}
      />
    );
  }

  return (
    <SummaryOverviewBox
      boxId={id}
      stepId={stepId}
      userData={userData}
      boxItems={boxItems}
      title={title}
    />
  );
};

export default SummaryOverviewBoxWrapped;
